version: '3'
services:
  nodejs:
    image: indiewebconsult/nodejs:latest
    build:
      context: base/nodejs/latest

  dncr:
    image: indiewebconsult/dotnetcore-runtime:latest
    environment:
      - "DOTNET_VERSION=2.2.3"
    build:
      context: base/nodejs/latest/dotnet-core-runtime

  dncsdk:
    image: indiewebconsult/dotnetcore-sdk:latest
    environment:
      - "DOTNET_SDK_VERSION=2.2.202"
    volumes:
      - ./samples/dotnetapp:/app
    build:
      context: base/nodejs/latest/dotnet-core-runtime/dotnet-core-sdk
  
  asp:
    image: indiewebconsult/aspdotnetcore:latest
    environment:
      - "ASPNETCORE_VERSION=2.2.3"
    volumes:
      - ./samples/aspnetapp:/app
    build:
      context: base/nodejs/latest/dotnet-core-runtime/dotnet-core-sdk/aspnet
  
  nginx:
    image: indiewebconsult/aspdotnetcore:latest-nginx
    environment:
      - "NGINX_VERSION=1.15.10"
    volumes:
      - ./samples/aspnetapp:/app
    build:
      context: base/nodejs/latest/dotnet-core-runtime/dotnet-core-sdk/aspnet/nginx